var reg_validate=function(c,e){function d(a,b){b.find(".help-inline").remove();b.append('<span class="help-inline">'+a+"</span>");return!1}function h(a){i&&g.find(a).trigger("blur")}function n(a){for(var b=0,a=a.split(""),d=0;d<a.length;d++)299>a[d].charCodeAt(0)?b++:b+=2;return b}var g=$(c);g.find("input");var p=g.find(".rd"),i=!1,j=0,k=!1,l=!1,f=[],f={IS_EMAIL_TIP:"如：gaofen@gaofen.com",IS_EMAIL_NULL:"请填写邮箱地址",IS_EMAIL_ERROR:"请填写正确的邮箱地址，用于找回密码",IS_EMAIL_EXIST:"此邮箱已被注册",IS_PASSWORD_TIP:"6-15位字符，可由英文、数字及标点符号组成",
IS_PASSWORD_NULL:"请设置密码",IS_PASSWORD_ERROR:"6-15位字符，可由英文、数字及标点符号组成",IS_CODE_TIP:"请输入图片中的字符，不区分大小写",IS_CODE_NULL:"请输入图片中的字符，不区分大小写",IS_CODE_ERROR:"验证码不正确，请检查",IS_USER_TIP:"4-15位字符，可由英文、中文及数字组成",IS_USER_NULL:"请填写昵称",IS_USER_ERROR:"4-15位字符，可由英文、中文及数字组成",IS_USER_ERROR1:"用户名包含敏感字符",IS_USER_ERROR2:"用户名包含敏感字符",IS_USER_ERROR3:"用户名已经存在",IS_USER_CONFIRM:"该昵称已被使用",IS_USER_NO_LEGAL:"用户名不合法",IS_USER_NO_ALLOW:"包含不允许注册的词语",IS_RESIDENCE_NULL:"请选择你的地域",IS_IDENTITY_NULL:"请选择您的身份",IS_DEAL_CHECK:"请先阅读《用户协议》"};g.find("#regEmail").bind({blur:function(){var a=
$(this),b=$(this).parents(".form-row"),c=$.trim($(this).val());if(c===k)i&&(j++,g.find("#username").trigger("blur"));else if(""==a.val())d(f.IS_EMAIL_NULL,b.removeClass("hints success").addClass("error")),h("#username");else{var e;e=a.val();e=/.+@.+\.[a-zA-Z]{2,4}$/.test(e)?!1:!0;e&&""!=a.val()?(d(f.IS_EMAIL_ERROR,b.removeClass("hints success").addClass("error")),h("#username")):(k=c,$.get("index.php?mod=user&do=checkName&type=1&username="+c,function(a){1!=a&&""!=a?(d(f.IS_EMAIL_EXIST,b.removeClass("hints success").addClass("error")),
h("#username")):(k=k==c?k:!1,i&&j++,b.removeClass("hints error").addClass("success"));h("#username")}))}},focus:function(){var a=$(this);j=0;""==a.val()&&(a=$(this).parents(".form-row"),d(f.IS_EMAIL_TIP,a.addClass("hints")))}});g.find("#regPassword").bind({blur:function(){var a=$(this),b=$(this).parents(".form-row");""==a.val()?d(f.IS_PASSWORD_NULL,b.removeClass("hints success").addClass("error")):6>a.val().length||15<a.val().length?d(f.IS_PASSWORD_ERROR,b.removeClass("hints success").addClass("error")):
b.removeClass("hints error").addClass("success")},focus:function(){if(""==$(this).val()){var a=$(this).parents(".form-row");d(f.IS_PASSWORD_TIP,a.addClass("hints"))}}});g.find("#username").bind({blur:function(){var a=$(this),b=$(this).parents(".form-row"),c=$.trim($(this).val());c===l?i&&(j++,g.find("#checkCode").trigger("blur")):""==a.val()?(d(f.IS_USER_NULL,b.removeClass("hints success").addClass("error")),h("#checkCode")):4>n(a.val())||15<n(a.val())?(d(f.IS_USER_ERROR,b.removeClass("hints success").addClass("error")),
h("#checkCode")):(l=c,$.post("index.php?mod=user&do=checkName&type=2&username="+a.val(),function(a){-1==a?d(f.IS_USER_ERROR1,b.removeClass("hints success").addClass("error")):-2==a?d(f.IS_USER_ERROR2,b.removeClass("hints success").addClass("error")):-3==a?d(f.IS_USER_ERROR3,b.removeClass("hints success").addClass("error")):(l=l==c?l:!1,i&&j++,b.removeClass("hints error").addClass("success"));h("#checkCode")}))},focus:function(){var a=$(this);j=0;""==a.val()&&(a=$(this).parents(".form-row"),d(f.IS_USER_TIP,
a.addClass("hints")))}});p.bind({click:function(){var a=$('input[name="status"]:checked').attr("checked"),b=$(this).parents(".form-row");a?(d("身份",b),b.removeClass("hints error").addClass("success")):d(f.IS_IDENTITY_NULL,b.removeClass("hints success").addClass("error"))},blur:function(){$(this).triggerHandler("click")}});g.find("#resideprovince").bind({blur:function(){var a=$(this),b=$(this).parents(".form-row");if(""==a.val())return d(f.IS_RESIDENCE_NULL,b.removeClass("hints success").addClass("error")),
!1},change:function(){var a=$(this).parents(".form-row");d("省份",a);a.removeClass("hints error").addClass("success")}});var m=null;g.find("#checkCode").bind({blur:function(){$(this);var a=$(this).parents(".form-row");""==this.value?(i&&(i=!1),d(f.IS_CODE_NULL,a.removeClass("hints success").addClass("error"))):(m&&m.abort(),m=$.get("index.php?mod=user&do=checkCode&code="+this.value,function(b){m=null;if("ok"!=b&&""!=b)i&&(i=!1),d("验证码不正确，请检查",a.removeClass("hints success").addClass("error"));else if(j++,
a.removeClass("hints error").addClass("success"),i)if(0==$("#reg_form .error").length)i=!1,$("#reg_form input[type='submit']").addClass("hidden").before('<span id="span_submit" class="btn btn-disabled">处理中...</span>'),e();else return!1}))},focus:function(){if(""==$(this).val()){var a=$(this).parents(".form-row");d(f.IS_CODE_TIP,a.addClass("hints"))}}});g.find("#user_agree").bind({click:function(){$("#user_agree").attr("checked")?($("input[type='submit']").removeAttr("disabled","disabled"),$("input[type='submit']").addClass("btn-primary")):
($("input[type='submit']").attr("disabled","disabled"),$("input[type='submit']").removeClass("btn-primary"))},focus:function(){$("#user_agree").attr("checked")||$("input[type='submit']").removeClass("btn-primary")}});$("#reg_form input[type='submit']").click(function(){i=!0;j=0;g.find("#regPassword").trigger("blur");g.find(".rd").trigger("blur");g.find("#resideprovince").trigger("blur");g.find("#regEmail").trigger("blur");g.find("#user_agree").trigger("focus");return!1})};
function isUndefined(c){return"undefined"==typeof c?!0:!1}function showdistrict(c,e,d,h){$("#"+c);c=function(c){c=c.find("option:selected");return c.eq.did||c.attr("did")||"0"};1<=h&&(e[0]&&$("#"+e[0]))&&c($("#"+e[0]));2<=h&&(e[1]&&$("#"+e[1]))&&c($("#"+e[1]));3<=h&&(e[2]&&$("#"+e[2]))&&c($("#"+e[2]));4<=h&&(e[3]&&$("#"+e[3]))&&c($("#"+e[3]));isUndefined(h)}
function showFirstDistrict(){$.get(APP_URL+"index.php?mod=common&do=showdistrict&first=1",function(c){$("#residedistrictbox").html($(c).find("root").text());$("#residedistrictbox #resideprovince").attr("tabindex","9");$("#residedistrictbox #residecity").attr("tabindex","10");$("#residedistrictbox #residedist").attr("tabindex","11")})}var addcss=function(){$(".sub_menu dd a").each(function(c){$(".sub_menu dd a").eq(c).click(function(){$(".sub_menu dd a").removeClass("selected");$(".sub_menu dd a").eq(c).addClass("selected")})})};
function trim(c){return c.replace(/^\s*(.*?)[\s\n]*$/g,"$1")};
