var fixDialog=function(a){var b=$(document.documentElement||document.body).width(),e=$(window).height(),a=$(a),c=a.width(),f=a.height();minX=0;maxX=b-c;centerX=maxX/2;minY=0;maxY=e-f;b=e*0.5-f/2;centerY=b>0?b:maxY/2;a.css({position:"absolute",display:"block",left:centerX,top:centerY,"z-index":1E4})},PopLayer=function(a){var b=document.documentElement,e;$("#pop_div").append($("<div id='overLay' style='display: block; background: #818181; z-index: 130; position: absolute; margin: 0px; padding: 0px; top: 0px; left: 0px;'><iframe frameborder='0' style='position:absolute; top:0; left:0; width:100%; height:100%; filter:alpha(opacity=0); opacity=0;'></iframe></div>"));
e=b.scrollHeight>b.clientHeight?b.scrollHeight:b.clientHeight;$("#pop_div").find("#overLay").css({width:b.clientWidth,height:e,opacity:0.8});var c=$(a);c.find(".close_btn").bind("click",function(){window.location="http://www.gaofen.com/shitibuy";$("#pop_div").css("display","none");c.css("display","none")});fixDialog(c)},reg_validate=function(a){function b(a,b){b.find(".help-inline").remove();b.append('<span class="help-inline">'+a+"</span>")}var e=$(a);e.find("input");e.find(".rd");var c=[],c={IS_USER_ERROR:"请填写收货人姓名",
IS_USER_ERROR1:"用户名不能多于 20 个字符",IS_USER_ERROR2:"用户名包含敏感字符",IS_MOBILE_ERROR:"请填写手机号码",IS_MOBILE_ERROR1:"手机号须为11位数字",IS_MOBILE_ERROR2:"手机号须为11位数字",IS_RESIDENCE_ERROR:"请选择区域",IS_ADDESS_ERROR:"请填写详细地址"};e.find("#slder_name").bind({blur:function(){var a=$(this),d=$(this).parents(".form-row");a.val()==""?b(c.IS_USER_ERROR,d.removeClass("hints success").addClass("error")):a.val().length>20?b(c.IS_USER_ERROR1,d.removeClass("hints success").addClass("error")):trim(a.val()).match(/<|"/ig)?b(c.IS_USER_ERROR2,
d.removeClass("hints success").addClass("error")):d.removeClass("hints error").addClass("success")},change:function(){$(this).triggerHandler("blur")}});e.find("#slder_phone").bind({blur:function(){var a=$(this),d=$(this).parents(".form-row");a.val()==""?b(c.IS_MOBILE_ERROR,d.removeClass("hints success").addClass("error")):a.val().length>11?b(c.IS_MOBILE_ERROR1,d.removeClass("hints success").addClass("error")):/^1[3|4|5|8][0-9]\d{4,8}$/.test(a.val())?d.removeClass("hints error").addClass("success"):
b(c.IS_MOBILE_ERROR2,d.removeClass("hints success").addClass("error"))},change:function(){$(this).triggerHandler("blur")}});e.find("#order_arae").bind({blur:function(){var a=$(this),d=$(this).parents(".form-row");a.val()==""?b(c.IS_RESIDENCE_ERROR,d.removeClass("hints success").addClass("error")):d.removeClass("hints error").addClass("success")},focus:function(){var a=$(this),d=$(this).parents(".form-row");a.val()==""?b(c.IS_RESIDENCE_ERROR,d.removeClass("hints success").addClass("error")):d.removeClass("hints error").addClass("success")},
change:function(){$(this).triggerHandler("blur")}});e.find("#address").bind({blur:function(){var a=$(this),d=$(this).parents(".form-row");a.val()==""?b(c.IS_ADDESS_ERROR,d.removeClass("hints success").addClass("error")):d.removeClass("hints error").addClass("success")},change:function(){$(this).triggerHandler("blur")}});$("#order_add_info").submit(function(){e.find("input").trigger("blur");e.find("#order_arae").trigger("blur");return $("#order_add_info .error").length>0?!1:($("#ord_btn").addClass("hidden").before('<span class="btn btn-disabled">处理中...</span>'),
!0)})};function trim(a){return a.replace(/^\s*(.*?)[\s\n]*$/g,"$1")}function jsRequestUrl(a){return a=a.indexOf("?")==-1?a+"?__rnd="+Math.random():a+"&__rnd="+Math.random()}function gaofen_shop_server(){$("#fbHandle").click(function(){var a=$(".shop-fixed");a.hasClass("fb-hide")?(a.removeClass("fb-hide").animate({right:0}),a.find("i").attr("title","收缩")):a.animate({right:-162},function(){$(this).addClass("fb-hide");$(this).find("i").attr("title","展开")})})}
$(function(){$("#fbHandle").click(function(){$(".tips").addClass("hidden");$(".action").removeClass("hidden");var a=$(".feedback");a.hasClass("fb-hide")?(a.removeClass("fb-hide").animate({right:0}),a.find("i").attr("title","收缩")):a.animate({right:-161},function(){$(this).addClass("fb-hide");$(this).find("i").attr("title","展开")})})});
function goodshop(a,b){if(a==="100019")alert("请先登录！"),location.href="http://my.gaofen.com/signin?fromurl="+location.href;else if(a=="0"){var e="http://www.gaofen.com/result/"+$("#product_id").val()+".htm",c=location.href.split("?");c.length>1&&(e+="?"+c[1]);window.location.href=e}else a=="1"?window.location.href=b:(alert("订单提交失败,"+b),$("#ord_btn").removeAttr("disabled"))};
